---
name: ✨ Feature Request
about: Request a new feature or an improvement to an existing one.
title: 'Feature: '
labels: 'type | feature'
---
## Summary
<!-- Brief explanation of the enhancement. -->

### Further Information
<!-- Provide any other additional information needed. -->

### Motivation
<!-- Why should this be added/changed? -->

